-- Membuat tabel orders
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  phone text not null,
  address text not null,
  laundry_type text not null, -- Jenis pakaian (Kiloan, Satuan, Dry Clean, dll)
  payment_method text not null,
  status text default 'Diproses'
);

-- Mematikan RLS sementara (agar bisa insert tanpa login auth ribet dulu untuk testing)
alter table public.orders enable row level security;
create policy "Enable read/write for all" on "public"."orders"
as permissive for all
to public
using (true)
with check (true);