create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nama text not null,
  no_telp text not null,
  alamat_lengkap text,
  detail_lokasi text, 
  layanan text, 
  berat_items text, 
  tgl_ambil text,
  tgl_antar text,
  waktu_jemput text
);

UPDATE profiles
SET role = 'admin'
WHERE email = 'user@admin.gmail.com';

ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS nama_kurir text;