// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6HzFIzoRU0Ae5STckZWHrL--6FkNTESw',
    appId: '1:522641273946:web:09a5ea0cbb6941eac3d463',
    messagingSenderId: '522641273946',
    projectId: 'modul1-64236',
    authDomain: 'modul1-64236.firebaseapp.com',
    storageBucket: 'modul1-64236.firebasestorage.app',
    measurementId: 'G-YBQSN55SQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYQ5B00vhmDWRwth0Z0sLO8tDYj7P_iWE',
    appId: '1:522641273946:android:5cc4d784db81cb39c3d463',
    messagingSenderId: '522641273946',
    projectId: 'modul1-64236',
    storageBucket: 'modul1-64236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-hgxxd399KNb2NSjN_DB2vVY_veOMEM',
    appId: '1:522641273946:ios:b3a7f57d5b7b901ac3d463',
    messagingSenderId: '522641273946',
    projectId: 'modul1-64236',
    storageBucket: 'modul1-64236.firebasestorage.app',
    iosBundleId: 'com.example.demo5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6HzFIzoRU0Ae5STckZWHrL--6FkNTESw',
    appId: '1:522641273946:web:e62bd618eded6f8ec3d463',
    messagingSenderId: '522641273946',
    projectId: 'modul1-64236',
    authDomain: 'modul1-64236.firebaseapp.com',
    storageBucket: 'modul1-64236.firebasestorage.app',
    measurementId: 'G-VGF7M02HRE',
  );
}
